after_success:
- mvn coveralls:report
before_script:
- sudo /etc/init.d/mysql stop
- ./travis/docker_bootstrap.sh
cache:
  directories:
  - $HOME/.m2
env:
  matrix:
  - MODULE=!querydsl-scala PROFILES=all,travis,examples
  - MODULE=!querydsl-jpa-codegen PROFILES=jpa,hibernate5,travis,examples
  - MODULE=querydsl-scala PROFILES=all,travis
install: /bin/true
jdk:
- oraclejdk8
language: java
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- mvn --batch-mode test --activate-profiles ${PROFILES} --projects ${MODULE} jacoco:report
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
services:
- docker
sudo: required
