addons:
  postgresql: '9.3'
after_success:
- mvn coveralls:report
before_script:
- mysql -u root -e "source travis/mysql.sql"
- psql -U postgres -f travis/postgresql.sql
- psql -c 'create extension postgis;' -d querydsl -U postgres
- ./travis/cubrid.sh
- ./travis/firebird.sh
cache:
  directories:
  - $HOME/.m2
env:
  matrix:
  - MODULE=!querydsl-scala PROFILES=all,travis,examples
  - MODULE=!querydsl-jpa-codegen PROFILES=jpa,hibernate5,travis,examples
  - MODULE=querydsl-scala PROFILES=all,travis
install:
- mvn -B -q --projects ${MODULE} -P${PROFILES} install -DskipTests=true
jdk:
- oraclejdk8
language: java
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- mvn -B test -P${PROFILES} --projects ${MODULE} jacoco:report
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
services:
- mongodb
sudo: required
